steps:
  - id: 'gateway-test-dev'
    name: gradle:8.13-jdk21
    dir: ./microservices/gateway
    entrypoint: gradle
    args: [ 'test' ]

  - id: 'gateway-assemble-dev'
    name: gradle:8.13-jdk21
    dir: ./microservices/gateway
    entrypoint: gradle
    args: [ 'assemble' ]

  - id: 'gateway-build-docker-image-dev'
    name: gcr.io/cloud-builders/docker
    dir: ./microservices/gateway
    args: [ 'build', '-t', 'europe-central2-docker.pkg.dev/democloudproject-gcp/docker-repo/gateway-dev', '--build-arg=JAR_FILE=build/libs/gateway-0.0.1-SNAPSHOT.jar', '.' ]

  - id: 'gateway-deploy-dev'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instance-groups
      - managed
      - rolling-action
      - start-update
      - gateway-mig-dev
      - --version-template=$(gcloud compute instance-templates list --filter="name~'gateway-container-template-dev'" --format="value(name)" | tail -1)
      - --region=europe-central2

images: [ 'europe-central2-docker.pkg.dev/democloudproject-gcp/docker-repo/gateway-dev' ]
#images:
#  - 'gcr.io/$PROJECT_ID/gateway-dev:latest'

options:
  logging: CLOUD_LOGGING_ONLY

#  # deploy container image to GKE
#  - name: "gcr.io/cloud-builders/gke-deploy"
#    args:
#      - run
#      - --filename=kubernetes-resource-file
#      - --location=location
#      - --cluster=cluster
